preload = ~/Downloads/fondo.jpg

# Opción A (Bloque moderno de Hyprpaper)
wallpaper {
    monitor = 
    path = ~/Downloads/fondo.jpg
    fit_mode = cover
}

# Opción B (Línea clásica por si usas una versión anterior)
wallpaper = ,~/Downloads/fondo.jpg

splash = false

